2020-05-06 11:04:38 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for audiconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 11:04:38 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 11:04:38 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for apple_tv which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 11:04:38 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 11:04:39 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 11:04:46 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 176: headers=self._headers, json=app_details)
2020-05-06 11:04:48 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:04:48 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 221: r = requests.post('https://%s-disp.coolkit.cc:8080/dispatch/app' % self._api_region, headers=self._headers)
2020-05-06 11:04:49 WARNING (MainThread) [homeassistant.components.lovelace] Resources need to be specified in your configuration.yaml. Please see the docs.
2020-05-06 11:04:52 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 11:04:52 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 11:04:52 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 11:04:52 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 11:04:52 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 11:04:52 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 11:04:52 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 11:04:52 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 11:04:52 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 11:04:52 WARNING (MainThread) [homeassistant.components.mqtt] Data in your configuration entry is going to override your configuration.yaml: {'broker': 'core-mosquitto', 'discovery': True, 'password': 'aupohjidohcoh1ahc0ootudoo2OofeeQu4eVah0nuWeVeinoogah0dei6JuJughi', 'port': 1883, 'protocol': '3.1.1', 'username': 'homeassistant'}
2020-05-06 11:04:52 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for google_geocode which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 11:04:52 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for jumbo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 11:04:52 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for plex_recently_added which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 11:04:52 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:04:52 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:04:53 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:04:53 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:04:54 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 62: api = JumboApi(username, password)
2020-05-06 11:04:54 ERROR (MainThread) [glances_api] Can not load data from Glances API
2020-05-06 11:04:54 WARNING (MainThread) [homeassistant.config_entries] Config entry for glances not ready yet. Retrying in 5 seconds.
2020-05-06 11:04:54 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:04:55 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:04:55 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:04:55 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:04:55 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:04:56 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:04:57 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:04:58 WARNING (MainThread) [homeassistant.setup] Setup of group is taking over 10 seconds.
2020-05-06 11:04:58 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2020-05-06 11:04:59 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:04:59 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:04:59 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:05:00 ERROR (MainThread) [glances_api] Can not load data from Glances API
2020-05-06 11:05:00 WARNING (MainThread) [homeassistant.config_entries] Config entry for glances not ready yet. Retrying in 5 seconds.
2020-05-06 11:05:00 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform squeezebox is taking over 10 seconds.
2020-05-06 11:05:01 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 5 seconds.
2020-05-06 11:05:03 WARNING (MainThread) [homeassistant.components.calendar] Setup of calendar platform google is taking over 10 seconds.
2020-05-06 11:05:07 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:05:07 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:05:09 WARNING (MainThread) [homeassistant.setup] Setup of hacs is taking over 10 seconds.
2020-05-06 11:05:10 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Unable to obtain the vehicle climatisation state for WAUZZZF48GA044048: 403, message='Forbidden', url='https://msg.volkswagen.de/fs-car/bs/climatisation/v1/Audi/DE/vehicles/WAUZZZF48GA044048/climater
2020-05-06 11:05:11 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Unable to obtain the vehicle charger state for WAUZZZF48GA044048: 403, message='Forbidden', url='https://msg.volkswagen.de/fs-car/bs/batterycharge/v1/Audi/DE/vehicles/WAUZZZF48GA044048/charger
2020-05-06 11:05:23 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:05:23 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:05:25 ERROR (MainThread) [glances_api] Can not load data from Glances API
2020-05-06 11:05:25 WARNING (MainThread) [homeassistant.config_entries] Config entry for glances not ready yet. Retrying in 10 seconds.
2020-05-06 11:05:27 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:27 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:27 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:27 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:27 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:27 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:27 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:27 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:27 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:27 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:27 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:28 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:28 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:28 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:28 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:28 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:28 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:28 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:28 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:28 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:28 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:28 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 11:05:30 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 10 seconds.
2020-05-06 11:05:40 WARNING (MainThread) [homeassistant.components.ps4.media_player] PS4 could not be reached
2020-05-06 11:05:49 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:05:55 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:05:55 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:06:16 ERROR (MainThread) [frontend.js.latest.202004272] https://casatinus.duckdns.org/local/community/bar-card/bar-card.js:5335:1 Uncaught SyntaxError: Unexpected token 'export'
2020-05-06 11:06:50 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:06:59 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:06:59 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:07:17 ERROR (MainThread) [frontend.js.latest.202004272] https://casatinus.duckdns.org/local/community/bar-card/bar-card.js:5335:1 Uncaught SyntaxError: Unexpected token 'export'
2020-05-06 11:07:51 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:08:51 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:09:00 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:09:00 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:09:52 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:09:55 ERROR (stream_worker) [homeassistant.components.stream.worker] Error demuxing stream: No dts in packet
2020-05-06 11:10:13 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2020-05-06 11:10:34 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2020-05-06 11:10:53 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:10:55 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: Timeout error
2020-05-06 11:11:00 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:11:00 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:11:54 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:12:55 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:13:00 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:13:00 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:13:56 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:14:57 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:15:01 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:15:01 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:15:09 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:15:20 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:15:31 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:15:42 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:15:53 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:15:57 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:16:04 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:16:15 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:16:26 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:16:37 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:16:48 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:16:58 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:16:59 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:17:01 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:17:01 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:17:10 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:17:21 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:17:32 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:17:43 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:17:53 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:17:59 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:18:04 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:18:15 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:18:26 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:18:37 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:18:48 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:18:59 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:19:00 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:19:01 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:19:01 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:19:10 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:19:21 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:19:32 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:19:43 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:19:54 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:19:57 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:19:57 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:19:57 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:19:58 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:19:58 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:20:01 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:20:05 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:20:16 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 11:21:02 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:21:02 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:21:02 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:22:03 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:23:02 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:23:02 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:23:04 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:24:05 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:24:09 ERROR (MainThread) [aioharmony.hubconnector] 10.0.1.197: Connection timed out for hub 14440977
2020-05-06 11:25:02 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:25:02 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:25:06 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:26:07 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:27:02 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:27:02 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:27:08 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:27:49 ERROR (MainThread) [frontend.js.latest.202004272] https://casatinus.duckdns.org/local/community/bar-card/bar-card.js:5335:1 Uncaught SyntaxError: Unexpected token 'export'
2020-05-06 11:28:09 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:29:02 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:29:02 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:29:10 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:29:18 ERROR (MainThread) [aioharmony.hubconnector] 10.0.1.197: Connection timed out for hub 14440977
2020-05-06 11:30:11 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:31:02 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:31:02 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:31:12 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:32:13 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:33:03 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:33:03 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:33:13 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:34:14 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:35:03 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:35:03 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:35:15 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:35:25 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:35:25 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:35:25 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:35:27 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:35:27 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 11:36:16 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:36:56 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.slaapkamer_raam is taking over 10 seconds
2020-05-06 11:36:56 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2020-05-06 11:36:56 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2020-05-06 11:37:03 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:37:03 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:37:17 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:38:18 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:38:28 ERROR (MainThread) [frontend.js.latest.202004272] https://casatinus.duckdns.org/local/community/bar-card/bar-card.js:5335:1 Uncaught SyntaxError: Unexpected token 'export'
2020-05-06 11:39:04 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 11:39:04 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 11:39:20 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 11:39:53 ERROR (MainThread) [frontend.js.latest.202004272] https://casatinus.duckdns.org/local/community/bar-card/bar-card.js:5335:1 Uncaught SyntaxError: Unexpected token 'export'
2020-05-06 11:40:20 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
